name: default-workflows

on:
  push:
    branches:
      - "**"

jobs:
  setup:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  test-and-build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: setup wasm32-wasi
        run: rustup target add wasm32-wasi

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          command: build-wasi
          args: --release
